#include "../../include/dfa/sql_dfa.h"

// sql_classify() :: generated by ChatGPT
sql_class_t sql_classify(const token_t *tok)
{
    switch (tok->kind)
    {
        case TOK_QUOTE:
            return SQL_C_QUOTE;

        case TOK_NUMBER:
            return SQL_C_NUMBER;

        case TOK_EQUALS:
            return SQL_C_COMPARE_OP;

        case TOK_WORD:
            if ((tok->len == 2 && strncasecmp(tok->start, "OR", 2) == 0) ||
                (tok->len == 3 && strncasecmp(tok->start, "AND", 3) == 0))
                return SQL_C_BOOL_OP;

            if (tok->len == 5 && strncasecmp(tok->start, "UNION", 5) == 0)
                return SQL_C_UNION;

            if (tok->len == 6 && strncasecmp(tok->start, "SELECT", 6) == 0)
                return SQL_C_SELECT;

            if (tok->len == 4 && strncasecmp(tok->start, "FROM", 4) == 0)
                return SQL_C_FROM;

            if (tok->len == 5 && strncasecmp(tok->start, "WHERE", 5) == 0)
                return SQL_C_WHERE;

            if (tok->len == 4 && strncasecmp(tok->start, "NULL", 4) == 0)
                return SQL_C_NULL;

            if ((tok->len == 4 && strncasecmp(tok->start, "LIKE", 4) == 0) ||
                (tok->len == 2 && strncasecmp(tok->start, "IS", 2) == 0) ||
                (tok->len == 2 && strncasecmp(tok->start, "IN", 2) == 0))
                return SQL_C_COMPARE_OP;

            if ((tok->len == 4 && strncasecmp(tok->start, "DROP", 4) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "DELETE", 6) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "INSERT", 6) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "UPDATE", 6) == 0) ||
                (tok->len == 5 && strncasecmp(tok->start, "ALTER", 5) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "CREATE", 6) == 0) ||
                (tok->len == 4 && strncasecmp(tok->start, "EXEC", 4) == 0) ||
                (tok->len == 7 && strncasecmp(tok->start, "EXECUTE", 7) == 0) ||
                (tok->len == 8 && strncasecmp(tok->start, "TRUNCATE", 8) == 0) ||
                (tok->len == 5 && strncasecmp(tok->start, "GRANT", 5) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "REVOKE", 6) == 0))
                return SQL_C_DANGEROUS_STMT;

            if ((tok->len == 5 && strncasecmp(tok->start, "SLEEP", 5) == 0) ||
                (tok->len == 9 && strncasecmp(tok->start, "BENCHMARK", 9) == 0) ||
                (tok->len == 8 && strncasecmp(tok->start, "PG_SLEEP", 8) == 0) ||
                (tok->len == 7 && strncasecmp(tok->start, "WAITFOR", 7) == 0) ||
                (tok->len == 5 && strncasecmp(tok->start, "DELAY", 5) == 0))
                return SQL_C_TIME_FUNC;

            if ((tok->len == 12 && strncasecmp(tok->start, "EXTRACTVALUE", 12) == 0) ||
                (tok->len == 9 && strncasecmp(tok->start, "UPDATEXML", 9) == 0) ||
                (tok->len == 8 && strncasecmp(tok->start, "DATABASE", 8) == 0) ||
                (tok->len == 7 && strncasecmp(tok->start, "VERSION", 7) == 0) ||
                (tok->len == 4 && strncasecmp(tok->start, "USER", 4) == 0) ||
                (tok->len == 6 && strncasecmp(tok->start, "SCHEMA", 6) == 0))
                return SQL_C_ERROR_FUNC;

            if ((tok->len == 18 && strncasecmp(tok->start, "INFORMATION_SCHEMA", 18) == 0) ||
                (tok->len == 13 && strncasecmp(tok->start, "SQLITE_MASTER", 13) == 0) ||
                (tok->len == 10 && strncasecmp(tok->start, "PG_CATALOG", 10) == 0) ||
                (tok->len == 10 && strncasecmp(tok->start, "SYSOBJECTS", 10) == 0) ||
                (tok->len == 10 && strncasecmp(tok->start, "TABLE_NAME", 10) == 0) ||
                (tok->len == 11 && strncasecmp(tok->start, "COLUMN_NAME", 11) == 0) ||
                (tok->len == 12 && strncasecmp(tok->start, "SCHEMA_NAME", 12) == 0))
                return SQL_C_METADATA;

            return SQL_C_WORD;

        case TOK_OTHER:
            if (tok->start[0] == '<' ||
                tok->start[0] == '>' ||
                tok->start[0] == '!')
                return SQL_C_COMPARE_OP;

            if (tok->start[0] == '-' && tok->len >= 2 && tok->start[1] == '-')
                return SQL_C_COMMENT;

            if (tok->start[0] == '#')
                return SQL_C_COMMENT;

            if (tok->start[0] == '/' && tok->len >= 2 && tok->start[1] == '*')
                return SQL_C_COMMENT;

            if (tok->start[0] == ';')
                return SQL_C_SEMICOLON;

            if (tok->start[0] == ',')
                return SQL_C_COMMA;

            if (tok->start[0] == '*')
                return SQL_C_STAR;

            if (tok->start[0] == '(')
                return SQL_C_PAREN_OPEN;

            if (tok->start[0] == ')')
                return SQL_C_PAREN_CLOSE;

            return SQL_C_OTHER;

        default:
            return SQL_C_OTHER;
    }
}


int check_sqli(lexer_t *lx)
{
    token_t tok;
    sql_state_t current_state = SQL_S_START;

    while (lexer_next(lx, &tok) != LEX_EOF)
    {
        sql_class_t cls = sql_classify(&tok);

        switch (current_state)
        {
            case SQL_S_START:
                if (cls == SQL_C_TIME_FUNC ||
                    cls == SQL_C_ERROR_FUNC ||
                    cls == SQL_C_METADATA)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else if (cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_SAW_BOUNDARY;
                }
                else if (cls == SQL_C_UNION)
                {
                    current_state = SQL_S_SAW_UNION;
                }
                else if (cls == SQL_C_SEMICOLON)
                {
                    current_state = SQL_S_SAW_SEMICOLON;
                }
                else if (cls == SQL_C_BOOL_OP)
                {
                    current_state = SQL_S_SAW_BOOL;
                }
                else if (cls == SQL_C_SELECT)
                {
                    current_state = SQL_S_SAW_SELECT;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_BOUNDARY:
                if (cls == SQL_C_BOOL_OP)
                {
                    current_state = SQL_S_SAW_BOOL;
                }
                else if (cls == SQL_C_UNION)
                {
                    current_state = SQL_S_SAW_UNION;
                }
                else if (cls == SQL_C_COMMENT)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else if (cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_SAW_BOUNDARY;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_BOOL:
                if (cls == SQL_C_WORD ||
                    cls == SQL_C_NUMBER ||
                    cls == SQL_C_NULL ||
                    cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_SAW_LHS;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_LHS:
                if (cls == SQL_C_COMPARE_OP)
                {
                    current_state = SQL_S_SAW_COMPARE;
                }
                else if (cls == SQL_C_WORD ||
                         cls == SQL_C_NUMBER ||
                         cls == SQL_C_NULL ||
                         cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_SAW_LHS;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_COMPARE:
                if (cls == SQL_C_WORD ||
                    cls == SQL_C_NUMBER ||
                    cls == SQL_C_NULL ||
                    cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_UNION:
                if (cls == SQL_C_SELECT)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else if (cls == SQL_C_WORD)
                {
                    current_state = SQL_S_SAW_UNION;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_SEMICOLON:
                if (cls == SQL_C_DANGEROUS_STMT ||
                    cls == SQL_C_SELECT ||
                    cls == SQL_C_UNION)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_SELECT:
                if (cls == SQL_C_METADATA)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else if (cls == SQL_C_FROM)
                {
                    current_state = SQL_S_SAW_FROM;
                }
                else if (cls == SQL_C_WORD ||
                         cls == SQL_C_NUMBER ||
                         cls == SQL_C_NULL ||
                         cls == SQL_C_QUOTE ||
                         cls == SQL_C_COMMA ||
                         cls == SQL_C_STAR)
                {
                    current_state = SQL_S_SAW_SELECT;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_SAW_FROM:
                if (cls == SQL_C_METADATA)
                {
                    current_state = SQL_S_ACCEPT;
                }
                else if (cls == SQL_C_WORD ||
                         cls == SQL_C_NUMBER ||
                         cls == SQL_C_NULL ||
                         cls == SQL_C_QUOTE)
                {
                    current_state = SQL_S_SAW_FROM;
                }
                else
                {
                    current_state = SQL_S_START;
                }
                break;

            case SQL_S_ACCEPT:
                return 1;

            default:
                current_state = SQL_S_START;
                break;
        }

        if (current_state == SQL_S_ACCEPT)
            return 1;
    }

    return 0;
}